### ISSUE TITLE
Modern code reviews in open-source projects: which problems do they fix?

### ISSUE THREAD

**Issue by CorbinSteele** [opensciences/opensciences.github.io#129]
### Paper Link:
http://dl.acm.org/citation.cfm?id=2597082
### Data Links:
+ http://dx.doi.org/10.6084/m9.figshare.915389

### Further Description:
http://figshare.com/articles/Code_Review_Defects/689805

**Comment by BenProvince** [comment]
# Context Notes
This data focuses on software _changes_ in response to defects, rather than the defects themselves.
http://dx.doi.org/10.6084/m9.figshare.915389

## Authors
Moritz Beller m.m.beller@tudelft.nl
Alberto Bacchelli a.bacchelli@tudelft.nl
Andy Zaidman a.e.zaidman@tudelft.nl
Elmar Juergens juergens@cqse.eu

## Datasets
These datasets reflect changes made to two software projects: ConQAT and GROMACS. These come from manually analyzed cases in TMS (Task Management System), which are sub-smpled due the large number of tasks for each product. The datasets changes_conqat_rand and changes_gromacs_rand each consist of a stratified random sample of 120 tasks from their respective projects, while changes_conqat_100 reflects the 100 most recently changed tasks from ConQAT.

These datasets are .odb databases, which can be opened with either LibreOffice Base or OpenOffice Base. Base is not included in the basic Ubuntu install of LibreOffice, but can be installed with "apt-get install libreoffice-base"

Each dataset includes two tables: 
-ISSUES lists issue numbers, authors, reviewers, the type of issue tracker, and whether the issue was valid.  
-REVIEWS lists issue numbers, sparse counts of the types of changes made according to the dichotomy below, and the number of self-motivated changes.

### Change Taxonomy
Here is a chart of the classification of change types, pulled from the original paper:
![Figure 3](https://www.dropbox.com/s/rvp4mq9eo1rcyv9/fig3_screenshot.png?)
Each type of change represented by columns in the REVIEWS table has a prefix corresponding to it's classification in this taxonomy. 
Examples:
-A comments change would be listed as "E_D_T_COMMENTS" where "E_D_T" corresponds to "Evolvability, Documentation, Textual"
-A GUI change would be listed as "F_LA_GUI" where "F_LA" corresponds to "Functional, Larger Defects"

**Comment by reesjones** [comment]
Added as ossreview.
http://openscience.us/repo/issues/ossreview.html
