### ISSUE TITLE
Characterizing and Predicting Blocking Bugs in Open Source Projects

### ISSUE THREAD

**Issue by WeiFoo** [opensciences/opensciences.github.io#159]
Paper link:http://dl.acm.org/citation.cfm?id=2597099&CFID=626469285&CFTOKEN=55193119

**Comment by Amoula1** [comment]
**Title: Characterizing and Predicting Blocking Bugs in Open Source Projects
**Link to the paper: http://users.encs.concordia.ca/~eshihab/pubs/Valdivia_MSR2014.pdf
**Author, email: 
Harold Valdivia Garcia: 
Emad Shihab: eshihab@cse.concordia.ca

**Objectives: The goal is to help developers identify blocking bugs as fast as possible.
** Main Contribution:  Studying blocking-bugs in six open source projects and proposition of a model to predict them.

** Evaluation Results: . Our results show that our prediction models achieve F-measures of 15-42%, which is a two to four-fold improvement over the baseline random predictors. We also find that the most important factors in determining blocking bugs are the comment text, comment size, the number of developers in the CC list of the bug report and the reporter’s experience.

**Datasets: Use of the the bug reports from Chromium, Eclipse, FreeDesktop, Mozilla, NetBeans and OpenOffice.
*The reason we chose these projects is because they are mature and long-lived open sources projects, with a large amount of bug reports. 
![image](https://cloud.githubusercontent.com/assets/10996072/6194783/788529ea-b395-11e4-9636-c37de3bb98ab.png)
