### ISSUE TITLE
Automatic verification of interactions in asynchronous systems with unbounded buffers

### ISSUE THREAD

**Issue by CarterPape** [opensciences/opensciences.github.io#227]
Paper link: http://dl.acm.org/citation.cfm?id=2643016

**Comment by rahulpandita** [comment]
###### *They have a prototype implementation and and some tests to go along with them. The data is in the form of tests.* May be for not for promise repo

Automatic Verification of Interactions in Asynchronous Systems with Unbounded Buffers [ASE 2014] . We present the necessary and sufficient condition under which asynchronously communicating systems with unbounded queues exhibit interaction behavior that is equivalent to their interactions over finitely bounded queues. We show that this condition can be automatically checked ensuring existence of a finite bound on the queue sizes, and we show that the finite bound on the queue sizes can be automatically computed. This allows automatic verification of the interaction behavior of the asynchronously communicating systems that conform to this condition, because interactions over unbounded queues can be simulated by interactions over finitely bounded queues. 

[Download Prototype](http://fmg.cs.iastate.edu/project-pages/async/release.02.09.tar.gz) implemented in [XSB](http://xsb.sourceforge.net/). Uncompressing the download will create a folder named: release.02.09. The folder contains

* src folder containing
 * main.P: top-level XSB file containing the analyzer
 * library.P: library functions necessary for the analyzer
 * cycle.P: algorithm for identifying unbounded send sequences
* example folder
* README

To write a new set of peers, use the following XSB syntax for representing transition relations of peers as facts: 
ptrans(peername, sourcestate, in(messagename, frompeer), destinationstate)
ptrans(peername, sourcestate, out(messagename, topeer), destinationstate)
The initial state of the peer is denoted by the fact
startPeer(peername, initialstate).
Add the necessary behavior in a file (say, test.P) and include the following in main.P
:- load_dyn('test.P');
