### ISSUE TITLE
 A dataset from change history to support evaluation of software maintenance tasks

### ISSUE THREAD

**Issue by reesjones** [opensciences/opensciences.github.io#380]
Paper link: http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=6624019

**Comment by vivekaxl** [comment]
Bogdan Dit, Andrew Holtzhauer, Denys Poshyvanyk
{bdit, asholtzh, denys}@cs.wm.edu
Huzefa Kagdi
kagdi@cs.wichita.edu

Title : A Dataset from Change History to Support Evaluation of Software Maintenance Tasks
Authors : Bogdan Dit, Andrew Holtzhauer, Denys Poshyvanyk, Huzefa Kagdi
Email :{bdit, asholtzh, denys}@cs.wm.edu, kagdi@cs.wichita.edu
Website : http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=6624019
Link To Dataset : http://www.cs.wm.edu/semeru/data/msr13/#datasets

@INPROCEEDINGS{6624019, 
author={Dit, B. and Holtzhauer, A. and Poshyvanyk, D. and Kagdi, H.}, 
booktitle={Mining Software Repositories (MSR), 2013 10th IEEE Working Conference on}, 
title={A dataset from change history to support evaluation of software maintenance tasks}, 
year={2013}, 
month={May}, 
pages={131-134}, 
keywords={Java;software maintenance;Java applications;SE tasks;change history;change request textual description;feature location;impact analysis;software engineering tasks;software maintenance tasks;source code;Benchmark testing;Gold;Java;Large scale integration;Software maintenance;Software systems;Generate Benchmarks;datasets;feature location;impact analysis}, 
doi={10.1109/MSR.2013.6624019}, 
ISSN={2160-1852},}


Approaches that support software maintenance need to be evaluated and compared against existing ones, in order to demonstrate their usefulness in practice. However, oftentimes the lack of well-established sets of benchmarks leads to situations where these approaches are evaluated using different datasets, which results in biased comparisons. In this data paper we describe and make publicly available a set of benchmarks from six Java applications, which can be used in the evaluation of various software engineering (SE) tasks, such as feature location and impact analysis. These datasets consist of textual description of change requests, the locations in the source code where they were implemented, and execution traces. Four of the benchmarks were already used in several SE research papers, and two of them are new. In addition, we describe in detail the methodology used for generating these benchmarks and provide a suite of tools in order to encourage other researchers to validate our datasets and generate new benchmarks for other subject software systems. Our online appendix: http://www.cs.wm.edu/semeru/data/msr13/.

Data Explanations: http://www.cs.wm.edu/semeru/data/msr13/#datasets
Promise Repo Category : software maintenance

**Comment by vivekaxl** [comment]
In this data paper, we want to address this problem and
provide six datasets from four open-source Java applications,
which can be used as benchmarks in the evaluation of various
software maintenance tasks, such as feature location, impact
analysis, developer recommendations, and traceability link
recovery. Our datasets contain textual descriptions of change
requests and locations in the source code where the change
requests were addressed. These datasets are ideal for evaluating
techniques based on Information Retrieval (IR). In addition, we
provide execution traces that were collected based on the
description of the change requests.

**Comment by reesjones** [comment]
Added as [maintenancebenchmarks](http://openscience.us/repo/other/maintenancebenchmarks.html)

**Comment by reesjones** [comment]
Data uploaded, authors emailed.
