### ISSUE TITLE
Safe software updates via multi-version execution

### ISSUE THREAD

**Issue by CarterPape** [opensciences/opensciences.github.io#429]
http://dl.acm.org/citation.cfm?id=2486869

**Comment by vivekaxl** [comment]
I don't see any data here. 
The paper deals with 
"We tackle this problem using a simple but effective multiversion
based approach. Whenever a new update becomes available,
instead of upgrading the software to the new version, we
run the new version in parallel with the old one; by carefully
coordinating their executions and selecting the behaviour of the
more reliable version when they diverge, we create a more secure
and dependable multi-version application."
