### ISSUE TITLE
	Detecting JavaScript races that matter

### ISSUE THREAD

**Issue by WeiFoo** [opensciences/opensciences.github.io#587]
http://delivery.acm.org/10.1145/2790000/2786820/p381-mutlu.pdf?ip=152.7.224.9&id=2786820&acc=ACTIVE%20SERVICE&key=6ABC8B4C00F6EE47%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35&CFID=725641379&CFTOKEN=87982003&__acm__=1446148953_b92b5c7dc02b6234fc1312de5f8b0d72

**Comment by junaidmaqbutt** [comment]
The paper basically used a crawler to fetch the top 5000 websites and then used an algorithm to find the top 26 websites based on the XML http requests. Then they used a benchmark tool to get the benchmark traces which they say is from 15MB to 400MB and this is their actual data. 

They then used this data to calculate their proposed study and test how is the rate of data races within a java script project. 

The problem is there is no actual link to the data. They do provide a link to a virtual machine and im assuming that machine will contain the data and they say it also contains the algorithm for getting the same results or to further continue the study
