### ISSUE TITLE
Users beware: preference inconsistencies ahead

### ISSUE THREAD

**Issue by vivekaxl** [opensciences/opensciences.github.io#628]
http://dl.acm.org/citation.cfm?id=2786869&CFID=550839757&CFTOKEN=78411605

**Comment by Iman-Es** [comment]
Authors have developed a configuration analysis tool, SCIC (Software Configuration Inconsistency Checker). There is no link to actual dataset. They have selected a 10-year period of the Mozilla core modules, 35 major releases of Firefox, from version 0.8 to version 34.0. (Since the core modules are also used within Firefox, and the release schedules for these two may be different, they have used
the Firefox versions as their baseline for evolution and studied the versions of the core modules that corresponded to those versions of Firefox.
