### ISSUE TITLE
Mining energy-greedy API usage patterns in Android apps: an empirical study

### ISSUE THREAD

**Issue by CorbinSteele** [opensciences/opensciences.github.io#71]
### Paper Link:
http://dl.acm.org/citation.cfm?id=2597085
### Data Links:
+ http://www.cs.wm.edu/semeru/data/MSR14-android-energy/

**Comment by timm** [comment]
# Data source

Mining energy-greedy API usage patterns in Android apps: an empirical study

# Link to the material associated with the dataset (if available)

+ [Data](http://www.cs.wm.edu/semeru/data/MSR14-android-energy/)
+ [Paper](http://dl.acm.org/citation.cfm?id=2597085)

# Attribution list for the material

+ Mario Linares-Vásquez,
Gabriele Bavota,
Carlos Bernal-Cárdenas3\,
Rocco Oliveto,
Massimiliano Di Penta,
Denys Poshyvanyk
+ mlinarev@cs.wm.edu, gbavota@unisannio.it, cebernalc@unal.edu.co,
rocco.oliveto@unimol.it, dipenta@unisannio.it, denys@cs.wm.edu
  

# BibTeX reference

````
@inproceedings{Linares-Vasquez:2014:MEA:2597073.2597085,
 author = {Linares-V\'{a}squez, Mario and Bavota, Gabriele and Bernal-C\'{a}rdenas, Carlos and Oliveto, Rocco and Di Penta, Massimiliano and Poshyvanyk, Denys},
 title = {Mining Energy-greedy API Usage Patterns in Android Apps: An Empirical Study},
 booktitle = {Proceedings of the 11th Working Conference on Mining Software Repositories},
 series = {MSR 2014},
 year = {2014},
 isbn = {978-1-4503-2863-0},
 location = {Hyderabad, India},
 pages = {2--11},
 numpages = {10},
 url = {http://doi.acm.org/10.1145/2597073.2597085},
 doi = {10.1145/2597073.2597085},
 acmid = {2597085},
 publisher = {ACM},
 address = {New York, NY, USA},
 keywords = {Empirical Study, Energy consumption, Mobile applications},
} 
````

# Link to the datasets

The authors offer [a very well structured web-site](http://www.cs.wm.edu/semeru/data/MSR14-android-energy/)  holding all the relevant codes and data.

# PROMISE repo category (effort, requirements, model, defect, etc.)

Code analysis

7. General overview of the data

Excessive energy consumption in mobile apps can be a consequence of energy greedy hardware, bad programming practices, or particular API usage patterns. We present the largest to date quantitative and qualitative empirical investigation into the categories of API calls and usage patterns that—in the context of the Android development framework—exhibit particularly high energy consumption profiles. By using a hardware power monitor, we measure energy consumption of method calls when executing typical usage scenarios in 55 mobile apps from different domains. Based on the collected data, we mine and analyze energy-greedy APIs and usage patterns. We zoom in and discuss the cases where either the anomalous energy consumption is unavoidable or where it is due to suboptimal usage or choice of APIs. Finally, we synthesize our findings into actionable knowledge and recipes for developers on how to reduce energy consumption while using certain categories of Android APIs and patterns

**Comment by reesjones** [comment]
Added as [apienergymining](http://openscience.us/repo/code-analysis/apienergymining.html).
